=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::CaoHunting
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CaoHunting' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::CaoHunting.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of CaoHunting' do
    it 'should create an instance of CaoHunting' do
      expect(@api_instance).to be_instance_of(Falcon::CaoHunting)
    end
  end

  # unit tests for aggregate_hunting_guides
  # Aggregate Hunting Guides
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [CaohuntingapiHuntingGuideAggregatesResponse]
  describe 'aggregate_hunting_guides test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aggregate_intelligence_queries
  # Aggregate intelligence queries
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [CaohuntingapiIntelligenceQueryAggregatesResponse]
  describe 'aggregate_intelligence_queries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_archive_export
  # Creates an Archive Export
  # @param language The Query Language. Accepted Values:  &lt;li&gt;cql&lt;/li&gt;&lt;li&gt;snort&lt;/li&gt;&lt;li&gt;suricata&lt;/li&gt;&lt;li&gt;yara&lt;/li&gt;&lt;li&gt;SPL &lt;i&gt;AI translated (Beta)&lt;/i&gt;&lt;/li&gt;&lt;li&gt;__all__ &lt;i&gt;returns a single archive with queries in all the languages&lt;/i&gt;&lt;/li&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter The FQL Filter
  # @option opts [String] :archive_type The Archive Type can be one of &#39;zip&#39; and &#39;gzip&#39;
  # @return [Array<Integer>]
  describe 'get_archive_export test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_hunting_guides
  # Retrieves a list of Hunting Guides
  # @param ids Hunting Guides IDs
  # @param [Hash] opts the optional parameters
  # @return [CaohuntingapiHuntingGuideEntityResponse]
  describe 'get_hunting_guides test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_intelligence_queries
  # Retrieves the details of a list of Intelligence queries IDs
  # @param ids Intelligence queries IDs
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :include_translated_content The AI translated language that should be returned if it exists&lt;br&gt;Accepted values are: &lt;li&gt;SPL&lt;/li&gt;&lt;li&gt;\\_\\_all\\_\\_&lt;/li&gt;
  # @return [CaohuntingapiIntelligenceQueryEntityResponse]
  describe 'get_intelligence_queries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_hunting_guides
  # Search for Hunting Guides that match the provided conditions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :offset Starting index of result set from which to return IDs.
  # @option opts [Integer] :limit Number of IDs to return.
  # @option opts [String] :sort Order by fields.
  # @option opts [String] :filter FQL query specifying the filter parameters.
  # @option opts [String] :q Match phrase_prefix query criteria; included fields: _all (all filter string fields indexed).
  # @return [MsaspecQueryResponse]
  describe 'search_hunting_guides test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_intelligence_queries
  # Search for a list of intelligence queries IDs that match the provided conditions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :offset Starting index of result set from which to return IDs.
  # @option opts [Integer] :limit Number of IDs to return.
  # @option opts [String] :sort Order by fields.
  # @option opts [String] :filter FQL query specifying the filter parameters.
  # @option opts [String] :q Match phrase_prefix query criteria; included fields: _all (all filter string fields indexed).
  # @return [MsaspecQueryResponse]
  describe 'search_intelligence_queries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
