=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::Iocs
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Iocs' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::Iocs.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of Iocs' do
    it 'should create an instance of Iocs' do
      expect(@api_instance).to be_instance_of(Falcon::Iocs)
    end
  end

  # unit tests for devices_count
  # Number of hosts in your customer account that have observed a given custom IOC
  # @param type  The type of the indicator. Valid types include:  sha256: A hex-encoded sha256 hash string. Length - min: 64, max: 64.  md5: A hex-encoded md5 hash string. Length - min 32, max: 32.  domain: A domain name. Length - min: 1, max: 200.  ipv4: An IPv4 address. Must be a valid IP address.  ipv6: An IPv6 address. Must be a valid IP address.
  # @param value The string representation of the indicator
  # @param [Hash] opts the optional parameters
  # @return [IocapiMsaReplyIOCDevicesCount]
  describe 'devices_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for devices_ran_on
  # Find hosts that have observed a given custom IOC. For details about those hosts, use GET /devices/entities/devices/v1
  # @param type  The type of the indicator. Valid types include:  sha256: A hex-encoded sha256 hash string. Length - min: 64, max: 64.  md5: A hex-encoded md5 hash string. Length - min 32, max: 32.  domain: A domain name. Length - min: 1, max: 200.  ipv4: An IPv4 address. Must be a valid IP address.  ipv6: An IPv6 address. Must be a valid IP address.
  # @param value The string representation of the indicator
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit The first process to return, where 0 is the latest offset. Use with the offset parameter to manage pagination of results.
  # @option opts [String] :offset The first process to return, where 0 is the latest offset. Use with the limit parameter to manage pagination of results.
  # @return [IocapiMsaReplyDevicesRanOn]
  describe 'devices_ran_on test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entities_processes
  # For the provided ProcessID retrieve the process details
  # @param ids ProcessID for the running process you want to lookup
  # @param [Hash] opts the optional parameters
  # @return [ProcessesapiMsaProcessDetailResponse]
  describe 'entities_processes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for processes_ran_on
  # Search for processes associated with a custom IOC
  # @param type  The type of the indicator. Valid types include:  sha256: A hex-encoded sha256 hash string. Length - min: 64, max: 64.  md5: A hex-encoded md5 hash string. Length - min 32, max: 32.  domain: A domain name. Length - min: 1, max: 200.  ipv4: An IPv4 address. Must be a valid IP address.  ipv6: An IPv6 address. Must be a valid IP address.
  # @param value The string representation of the indicator
  # @param device_id Specify a host&#39;s ID to return only processes from that host. Get a host&#39;s ID from GET /devices/queries/devices/v1, the Falcon console, or the Streaming API.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit The first process to return, where 0 is the latest offset. Use with the offset parameter to manage pagination of results.
  # @option opts [String] :offset The first process to return, where 0 is the latest offset. Use with the limit parameter to manage pagination of results.
  # @return [IocapiMsaReplyProcessesRanOn]
  describe 'processes_ran_on test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
