=begin
#CrowdStrike API Specification

#Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.

The version of the OpenAPI document: 2023-05-30T23:10:32Z

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::MobileEnrollmentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MobileEnrollmentApi' do
  before do
    # run before each test
    @api_instance = Falcon::MobileEnrollmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MobileEnrollmentApi' do
    it 'should create an instance of MobileEnrollmentApi' do
      expect(@api_instance).to be_instance_of(Falcon::MobileEnrollmentApi)
    end
  end

  # unit tests for request_device_enrollment_v3
  # Trigger on-boarding process for a mobile device
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :action_name Action to perform
  # @option opts [String] :filter FQL filter
  # @return [ApiPostEnrollmentDetailsResponse]
  describe 'request_device_enrollment_v3 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
