=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::NetworkScanTemplates
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NetworkScanTemplates' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::NetworkScanTemplates.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of NetworkScanTemplates' do
    it 'should create an instance of NetworkScanTemplates' do
      expect(@api_instance).to be_instance_of(Falcon::NetworkScanTemplates)
    end
  end

  # unit tests for create_templates
  # Create \&quot;templates\&quot; using provided specifications
  # @param body \&quot;templates\&quot; specifications
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @return [DomainTemplateEntitiesResponse]
  describe 'create_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_templates
  # Delete \&quot;templates\&quot; by their IDs
  # @param ids IDs of \&quot;templates\&quot; to be deleted (Min: 1, Max: 100)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @return [MsaspecQueryResponse]
  describe 'delete_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_template_configs
  # Get details on the network scan template configurations
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @return [MsaspecQueryResponse]
  describe 'get_template_configs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_templates
  # Get \&quot;templates\&quot; by their IDs
  # @param ids IDs of \&quot;templates\&quot; to be retrieved (Min: 1, Max: 100)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @return [DomainTemplateEntitiesResponse]
  describe 'get_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for query_templates
  # Get \&quot;templates IDs\&quot; by filter
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @option opts [Integer] :offset An offset used with the &#x60;limit&#x60; parameter to manage pagination of results. On your first request, don’t provide an &#x60;offset&#x60;. On subsequent requests, add previous &#x60;offset&#x60; with the previous &#x60;limit&#x60; to continue from that place in the results
  # @option opts [Integer] :limit The number of \&quot;templates IDs\&quot; to return in this response (Min: 1, Max: 100, Default: 100)
  # @option opts [String] :sort Sort \&quot;templates\&quot; by their properties. A single sort field is allowed
  # @option opts [String] :filter Search for \&quot;templates\&quot; by providing an FQL filter
  # @return [MsaspecQueryResponse]
  describe 'query_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_templates
  # Update \&quot;templates\&quot; using provided specifications
  # @param body \&quot;templates\&quot; specifications for updating
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_cs_useruuid User UUID
  # @return [DomainTemplateEntitiesResponse]
  describe 'update_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
