=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>

CrowdStrike Swagger API Version: 2023-05-30T23:10:32Z

=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::ScheduledReportsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScheduledReportsApi' do
  before do
    # run before each test
    @api_instance = Falcon::ScheduledReportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScheduledReportsApi' do
    it 'should create an instance of ScheduledReportsApi' do
      expect(@api_instance).to be_instance_of(Falcon::ScheduledReportsApi)
    end
  end

  # unit tests for scheduled_reports_get
  # Retrieve scheduled reports for the provided report IDs.
  # @param ids The scheduled_report id to get details about.
  # @param [Hash] opts the optional parameters
  # @return [DomainScheduledReportsResultV1]
  describe 'scheduled_reports_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for scheduled_reports_launch
  # Launch scheduled reports executions for the provided report IDs.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [DomainReportExecutionsResponseV1]
  describe 'scheduled_reports_launch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for scheduled_reports_query
  # Find all report IDs matching the query with filter
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Possible order by fields: created_on, last_updated_on, last_execution_on, next_execution_on
  # @option opts [String] :filter FQL query specifying the filter parameters. Filter term criteria: type, trigger_reference, recipients, user_uuid, cid, trigger_params.metadata. Filter range criteria: created_on, modified_on; use any common date format, such as &#39;2010-05-15T14:55:21.892315096Z&#39;.
  # @option opts [String] :q Match query criteria, which includes all the filter string fields
  # @option opts [String] :offset Starting index of overall result set from which to return ids.
  # @option opts [Integer] :limit Number of ids to return.
  # @return [MsaQueryResponse]
  describe 'scheduled_reports_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
