=begin
#CrowdStrike API Specification

#Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.

The version of the OpenAPI document: 2023-05-30T23:10:32Z

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::ZeroTrustAssessmentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ZeroTrustAssessmentApi' do
  before do
    # run before each test
    @api_instance = Falcon::ZeroTrustAssessmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZeroTrustAssessmentApi' do
    it 'should create an instance of ZeroTrustAssessmentApi' do
      expect(@api_instance).to be_instance_of(Falcon::ZeroTrustAssessmentApi)
    end
  end

  # unit tests for get_assessment_v1
  # Get Zero Trust Assessment data for one or more hosts by providing agent IDs (AID) and a customer ID (CID).
  # @param ids One or more agent IDs, which you can find in the data.zta file, or the Falcon console.
  # @param [Hash] opts the optional parameters
  # @return [DomainAssessmentsResponse]
  describe 'get_assessment_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_assessments_by_score_v1
  # Get Zero Trust Assessment data for one or more hosts by providing a customer ID (CID) and a range of scores.
  # @param filter FQL query specifying the filter score.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The number of scores to return in this response (min: 1, max: 1000, default: 100). Use with the &#x60;after&#x60; parameter to manage pagination of results.
  # @option opts [String] :after A pagination token used with the &#x60;limit&#x60; parameter to manage pagination of results. On your first request, don&#39;t provide an &#x60;after&#x60; token. On subsequent requests, provide the &#x60;after&#x60; token from the previous response to continue from that place in the results.
  # @option opts [String] :sort Sort accounts by their properties. A single sort field is allowed. Defaults to ascending. Supported sort option include:  &lt;ul&gt;&lt;li&gt;score|desc&lt;/li&gt;&lt;li&gt;score|asc&lt;/li&gt;&lt;/ul&gt;
  # @return [DomainAssessmentsByScoreResponse]
  describe 'get_assessments_by_score_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_audit_v1
  # Get the Zero Trust Assessment audit report for one customer ID (CID).
  # @param [Hash] opts the optional parameters
  # @return [DomainAuditResponse]
  describe 'get_audit_v1 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
