additionalProperties:
  gemAuthor: "CRWD Solution Architects"
  gemAuthorEmail: "cloud-integrations@crowdstrike.com"
  gemDescription: "Use CrowdStrike Falcon APIs to interact with Falcon platform."
  gemSummary: "CrowdStrike Falcon"
  gemLicense: "MIT License"
  gemHomepage: "https://github.com/CrowdStrike/crimson-falcon"
  gemVersion: "0.3.0" # x-release-please-version
  gemName: "crimson-falcon"
  moduleName: "Falcon"
