name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Install Gem
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: make build

      - name: Upload gem
        uses: actions/upload-artifact@v4
        with:
          name: crimson-gem-${{ matrix.ruby-version }}
          path: crimson-falcon*.gem
          if-no-files-found: error

      - name: Install gem
        run: make install
