name: RuboCop Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: 3.0 # Use the Ruby version you want here.

    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: rubocop
