# .github/workflows/test.yml
name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  pull_request_target:
    types: [labeled]

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby-version }}
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request_target' && github.event.label.name == 'ok-to-test')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Download gem artifact
        uses: actions/download-artifact@v4
        with:
          name: crimson-gem-${{ matrix.ruby-version }}

      - name: Install dependencies
        run: make install

      - name: Run tests
        env:
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
          FALCON_CLOUD: ${{ secrets.FALCON_CLOUD }}
        run: bundle exec rspec
